### ISSUE TITLE
No permission

### ISSUE THREAD

**Issue by JapSeyz** [evgeny-golubev/Laravel-4-Artisan#10]
When i try to run artisan migrate:make (create_users_table)  - the text in  brackets is entered in the console like thing -

[Errno 13] Permission denied
[cmd: ['/Applications/MAMP/bin/php/php5.5.3/bin', '/Applications/MAMP/htdocs/Dyvke/artisan', 'migrate:make', 'create_users_table']]
[dir: /Applications/MAMP/htdocs/Dyvke]
[path: /usr/bin:/bin:/usr/sbin:/sbin]
[Finished]

I am not sure how to give this sudo perms.

**Comment by evgeny-golubev** [comment]
You need fix permissions in your system. I can't help you in simple way.
