### ISSUE TITLE
Cannot find custom command

### ISSUE THREAD

**Issue by ghost** [evgeny-golubev/Laravel-4-Artisan#11]
I'm having some troubles executing my custom command. I added this in my commands - user:

[
    "caption": "Migration Refresh & Seed",
    "command": "laravel_refresh",
    "args": [
        "command": "migrate:refresh --seed"
    ]
]

However, I cannot find "laravel_refresh" when I try to execute. How can I fix this?

Thank you for the great plugin!

**Comment by evgeny-golubev** [comment]
Your command must be in this format:

``` json
[
    {
        "caption": "Migration Refresh & Seed",
        "command": "laravel4_artisan",
        "args": {
            "command": "migrate:refresh --seed"
        }
    }
]
```
