### ISSUE TITLE
[RuntimeException] Aborted

### ISSUE THREAD

**Issue by ghost** [evgeny-golubev/Laravel-4-Artisan#13]
Hello,

I've got a problem generating a resource (or scaffold). Every other generation works nice!
- PHP is running (xampp) on Windows.
- The path to PHP is set manually, even if only "php" would do the job.
- Artisan ist availabe in the project root or Laravel,
- I can run artisan commands AND generate a resource in the terminal!

Hopefully I've covered everything. The only problem now is that I can't generate a resource through ST. Here is the error:

---

Do you want me to create a Ben model? [yes|no]

  [RuntimeException]  
  Aborted             

generate:resource [--fields[="..."]] resource

[Finished in 0.5s]

---

Do you guys have any ideas why it just doesn't work in ST?!

**Comment by evgeny-golubev** [comment]
Sorry, but this package not tested on windows and is not planned. You can help with the problems by pull requests with fixes.

**Comment by GRAgmLauncher** [comment]
Any chance to reconsider adding this for windows? For Linux/Mac, vim seems to be more popular, while Sublime text is very useful on Windows.

I would do it myself, but I don't know nearly enough about Python to figure out what might be wrong.

**Comment by evgeny-golubev** [comment]
This is my "home project" and i use this plugin on OS X. You can always support it by pull request.
