### ISSUE TITLE
Error: "Mcrypt PHP extension required."

### ISSUE THREAD

**Issue by OKNoah** [evgeny-golubev/Laravel-4-Artisan#17]
I get this error when running the commands

```
create_users_table
username:string, password:string, email:string
```

I have used `phpinfo()` and `php -m`, as well as `which php` and `/etc/apache2/httpd.conf` to confirm I have mccrypt installed and that the command line php and apache php are the same.

EDIT: Can someone tell me how to do the same thing on the command-line so I can see if the problem is Artisan or the plugin?

**Comment by evgeny-golubev** [comment]
Verify your php path in configuration. Use full path if you get this error with standard 

``` json
{
    "php_path": "php",
    "artisan_path": "artisan"
}
```

**Comment by OKNoah** [comment]
I put the follow in my default and user settings, but no joy.

```
{
    "php_path": "/usr/local/Cellar/php55/5.5.13/bin/php",    
    "artisan_path": "artisan"
}
```

EDIT: Closed and re-opened project and it seems to have worked.

**Comment by evgeny-golubev** [comment]
Use follow for future updates php:

``` json
{
    "php_path": "/usr/local/bin/php",    
    "artisan_path": "artisan"
}
```
