### ISSUE TITLE
migrate:refresh error... 

### ISSUE THREAD

**Issue by aasanchez** [evgeny-golubev/Laravel-4-Artisan#18]
---
-          *
  ************

---
-          *
  ************

Do you really wish to run this command? 

  [RuntimeException]  
  Aborted             

migrate:refresh [--database[="..."]] [--force] [--seed] [--seeder[="..."]]

[Finished in 0.1s]

**Comment by GramMKII** [comment]
I'm on windows and i'm having the same problem with:
・migrate
・migrage:refresh
・migrate:reset
・migrate:rollback

I get:
  Do you really wish to run this command? 
  [RuntimeException]  
  Aborted  

The commands work fine when using the command prompt though.

**Comment by GramMKII** [comment]
I somehow made it work by editing the sublime_commands file and adding the `no-interaction` option on the command. 
`Migrate:refresh` is still broken though because `Migrate:refresh` still asks for a confirmation even with the `no-interaction` option set.
