### ISSUE TITLE
[Request] Add settings file for specifying php path

### ISSUE THREAD

**Issue by JohannesMP** [evgeny-golubev/Laravel-4-Artisan#2]
For development I use the php provided by my MAMP installation, which lives at `/Applications/MAMP/bin/php/php5.4.10/bin/php`.

Unfortunately 'Laravel 4 Artisan' has `php` hardcoded. While I do modify the PATH variable in `.bash_profile` so that the php command looks in the MAMP location instead of the default that lives at `/usr/bin/php`, when the script executes it does not use the settings defined in .bash_profile, and so my default php is used.

A similar sublime text 2 package "Laravel Generator" gets around this by providing a settings file where you can easily modify `php_path`. However this package does not contain nearly as many features, so I would prefer using yours if possible.

I would like to request that you please add a similar settings file so that users don't have to manually edit the python code to change their php path (which is how I am currently using Laravel 4 Artisan)

**Comment by evgeny-golubev** [comment]
Settings added. Thank you.
