### ISSUE TITLE
Laravel Generate: Controller Error

### ISSUE THREAD

**Issue by ctf0** [evgeny-golubev/Laravel-4-Artisan#23]
if i added `Route::controller('photo', 'PhotoController')` first to the routes then tried `Laravel Generate: Controller`, i get this error

```
{"error":{"type":"ReflectionException","message":"Class PhotoController does not exist","file":"\/Applications\/AMPPS\/www\/Laravel\/All-In-One-Project\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/ControllerInspector.php","line":28}}[Finished in 0.2s]
```

but if i made `Route::resource` then tried the same cmnd all goes well and the controller file gets created without any errors , any thoughts why this happens ?

**Comment by evgeny-golubev** [comment]
Generate controller before use it.
