### ISSUE TITLE
[Request] Modify 'Custom Command' to display output.

### ISSUE THREAD

**Issue by JohannesMP** [evgeny-golubev/Laravel-4-Artisan#3]
Currently the command `Laravel Artisan: Custom Command` does not output the result of the entered command. For example entering 'routes' after running `Laravel Artisan: Custom Command` does not display anything.

A similar package `Laravel Generators` manages to do this correctly with its command: `Laravel Artisan Command`. As a comparison, when entering `routes` in that package the routes information is correctly displayed.

**Comment by evgeny-golubev** [comment]
All output displayed in exec output panel. It is convenient for me and I do not see the point in changing the output similar to the `Laravel Generators` package. Thank you.

**Comment by evgeny-golubev** [comment]
Additional information in Notes section of README.md
https://github.com/m0nah/Laravel-4-Artisan/commit/8db858b9b001cdb9ecfeae180b93bd76f97d2da3
