### ISSUE TITLE
[Request] Sublime text 3 version

### ISSUE THREAD

**Issue by JohannesMP** [evgeny-golubev/Laravel-4-Artisan#4]
Although Sublime text 3 is still in development it would be nice to to have a version of Laravel 4 Artisan that can be installed via package control when using ST3.

Note: At the time of this writing laravel 4 artisan did not show up under package control, and was labelled as sublime text 2 only on https://sublime.wbond.net/packages/Laravel%204%20Artisan

**Comment by evgeny-golubev** [comment]
Laravel 4 Artisan work on Sublime Text 2 and 3 both.
