### ISSUE TITLE
New installation error

### ISSUE THREAD

**Issue by louposk** [evgeny-golubev/Laravel-4-Artisan#8]
Hello,
i have just installed from Sublime packages but when i try to run a command i get a message at the bottom of the editor: "Artisan not found".

I have in my settings fire the path to PHP: C:/wamp/bin/php/php5.3.13

Any ideas?

Thanks

**Comment by evgeny-golubev** [comment]
Hello,
As described in notes: `Artisan file needs to been in the root folder of your structure in the sidebar.`.
